import './globals.css'
import Toast from '@/components/ui/toast'

export const metadata = {
  title: 'Bonu Usarova',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-slate-950 antialiased font-roboto text-slate-400">
        <Toast>
          {children}
        </Toast>
      </body>
    </html>
  )
}
